version: '3.9'

services:
  web-app:
    build: 
      context: ./web-app
      args:
        NEXT_PUBLIC_AI_WEB_SOCKET_URL: ws://localhost:3004/ws
    ports:
      - "3000:3000"
    env_file:
      - ./web-app/docker.env


  background-job-service:
     build:
        context: ./background-job-service
     ports:
          - "3001:3001"
     env_file:
          - ./background-job-service/docker.env   

  intelligence-service:
    build:
      context: ./intelligence-service
    ports:
        - "3004:3004"
    env_file:
        - ./intelligence-service/docker.env

  embedding-service:
    build:
      context: ./embedding-service
    ports:
        - "3003:3003"
    env_file:
        - ./embedding-service/docker.env 

  video-processing-service:
    build:
      context: ./video-processing-service
    ports:
        - "3002:3002"
    env_file:
        - ./video-processing-service/docker.env      
