version: '3.9'

services:
  web-app:
    build: 
      context: ./web-app
      args:
        NEXT_PUBLIC_AI_WEB_SOCKET_URL: ws://localhost:3004/ws
    ports:
      - "3000:3000"
    env_file:
      - ./web-app/docker.env
    depends_on:
      - kafka-service


  background-job-service:
    build:
      context: ./background-job-service
    ports:
      - "3001:3001"
    env_file:
      - ./background-job-service/docker.env 
    depends_on:
      - kafka-service
    environment:
      KAFKA_BROKER: kafka-service:9092
  

  intelligence-service:
    build:
      context: ./intelligence-service
    ports:
        - "3004:3004"
    env_file:
        - ./intelligence-service/docker.env

  embedding-service:
    build:
      context: ./embedding-service
    ports:
        - "3003:3003"
    env_file:
        - ./embedding-service/docker.env   
       

  video-processing-service:
    build:
      context: ./video-processing-service
    ports:
        - "3002:3002"
    env_file:
        - ./video-processing-service/docker.env

  kafka-service:
    image: apache/kafka:3.9.0
    container_name: kafka-broker
    ports:
      - "9092:9092"